"""Domain-facing records detached from SQLAlchemy sessions."""

from .vacancy_contract import (
    CONTRACT_VERSION,
    EMPLOYMENT_VALUES,
    EXPERIENCE_VALUES,
    WORK_FORMAT_VALUES,
    EmploymentCode,
    ExperienceCode,
    NormalizedVacancy,
    WorkFormat,
)
from .entities import (
    OAuthConnectionRecord,
    SearchSnapshotCandidateRecord,
    SearchSnapshotItemRecord,
    SearchSnapshotRecord,
    SearchSnapshotSourceRecord,
    SourceRecord,
    SyncCheckpointRecord,
    SyncRunRecord,
    SyncWorkerRecord,
    UserRecord,
    VacancyRecord,
)
__all__ = [
    "CONTRACT_VERSION",
    "EMPLOYMENT_VALUES",
    "EXPERIENCE_VALUES",
    "WORK_FORMAT_VALUES",
    "EmploymentCode",
    "ExperienceCode",
    "NormalizedVacancy",
    "WorkFormat",
    "OAuthConnectionRecord",
    "SearchSnapshotCandidateRecord",
    "SearchSnapshotItemRecord",
    "SearchSnapshotRecord",
    "SearchSnapshotSourceRecord",
    "SourceRecord",
    "SyncCheckpointRecord",
    "SyncRunRecord",
    "SyncWorkerRecord",
    "UserRecord",
    "VacancyRecord",
]
